// Code generated by clisubcmd generator. DO NOT EDIT.

package card

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/akubi0w1/sge-tech-book-vol3-sample/internal/cli/cmd/grpc"
	"github.com/akubi0w1/sge-tech-book-vol3-sample/internal/terror"
	pb "github.com/akubi0w1/sge-tech-book-vol3-sample/pkg/pb/service"
	"github.com/spf13/cobra"
)

type Option struct {
	*grpc.Option
}

func NewCmd(parentOpt *grpc.Option) (*cobra.Command, *Option) {
	opt := &Option{
		Option: parentOpt,
	}

	cmd := &cobra.Command{
		Use:   "card",
		Short: "Call CardService rpc.",
		Long:  "Call CardService rpc.",
		Example: strings.Join([]string{
			fmt.Sprintf("%s grpc card <rpc_name> [-d '{}']", opt.RootCmdName),
		}, "\n"),
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) < 1 {
				return terror.Newf(terror.CodeInvalidArgument, "requires <rpc_name>")
			}
			rpcName := args[0]

			// get data body
			data, err := opt.RequestData()
			if err != nil {
				return err
			}

			grpcClient, err := opt.NewGRPCClient()
			if err != nil {
				return err
			}
			defer grpcClient.Close()

			client := pb.NewCardServiceClient(grpcClient)

			switch rpcName {
			case "DrawCard":
				return handleDrawCard(cmd.Context(), opt, client, data)
			case "ListCard":
				return handleListCard(cmd.Context(), opt, client, data)
			}

			return terror.Newf(terror.CodeInvalidArgument, "invalid rpc name.")
		},
	}

	return cmd, opt
}

func handleDrawCard(
	ctx context.Context,
	opt *Option,
	cli pb.CardServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.DrawCardRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal DrawCardRequest request.")
	}
	
	res, err := cli.DrawCard(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}

func handleListCard(
	ctx context.Context,
	opt *Option,
	cli pb.CardServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.ListCardRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal ListCardRequest request.")
	}
	
	res, err := cli.ListCard(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}
