// Code generated by clisubcmd generator. DO NOT EDIT.

package user

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/akubi0w1/sge-tech-book-vol3-sample/internal/cli/cmd/grpc"
	"github.com/akubi0w1/sge-tech-book-vol3-sample/internal/terror"
	pb "github.com/akubi0w1/sge-tech-book-vol3-sample/pkg/pb/service"
	"github.com/spf13/cobra"
)

type Option struct {
	*grpc.Option
}

func NewCmd(parentOpt *grpc.Option) (*cobra.Command, *Option) {
	opt := &Option{
		Option: parentOpt,
	}

	cmd := &cobra.Command{
		Use:   "user",
		Short: "Call UserService rpc.",
		Long:  "Call UserService rpc.",
		Example: strings.Join([]string{
			fmt.Sprintf("%s grpc user <rpc_name> [-d '{}']", opt.RootCmdName),
		}, "\n"),
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) < 1 {
				return terror.Newf(terror.CodeInvalidArgument, "requires <rpc_name>")
			}
			rpcName := args[0]

			// get data body
			data, err := opt.RequestData()
			if err != nil {
				return err
			}

			grpcClient, err := opt.NewGRPCClient()
			if err != nil {
				return err
			}
			defer grpcClient.Close()

			client := pb.NewUserServiceClient(grpcClient)

			switch rpcName {
			case "ListUser":
				return handleListUser(cmd.Context(), opt, client, data)
			case "GetUser":
				return handleGetUser(cmd.Context(), opt, client, data)
			case "CreateUser":
				return handleCreateUser(cmd.Context(), opt, client, data)
			case "UpdateUserName":
				return handleUpdateUserName(cmd.Context(), opt, client, data)
			}

			return terror.Newf(terror.CodeInvalidArgument, "invalid rpc name.")
		},
	}

	return cmd, opt
}

func handleListUser(
	ctx context.Context,
	opt *Option,
	cli pb.UserServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.ListUserRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal ListUserRequest request.")
	}
	
	res, err := cli.ListUser(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}

func handleGetUser(
	ctx context.Context,
	opt *Option,
	cli pb.UserServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.GetUserRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal GetUserRequest request.")
	}
	
	res, err := cli.GetUser(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}

func handleCreateUser(
	ctx context.Context,
	opt *Option,
	cli pb.UserServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.CreateUserRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal CreateUserRequest request.")
	}
	
	res, err := cli.CreateUser(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}

func handleUpdateUserName(
	ctx context.Context,
	opt *Option,
	cli pb.UserServiceClient,
	data []byte,
) error {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	req := new(pb.UpdateUserNameRequest)
	if err := json.Unmarshal(data, &req); err != nil {
		return terror.Wrapf(terror.CodeInvalidArgument, err, "failed to unmarshal UpdateUserNameRequest request.")
	}
	
	res, err := cli.UpdateUserName(ctx, req)
	if err != nil {
		opt.Logf("returns error from server.")
		opt.Logf("%+s", err)
		return nil
	}

	opt.Logf("returns success from server.")
	opt.Format(res)
	return nil
}
